from enum import Enum


class TestCategory(str, Enum):
    STATUS_CODE = "STATUS_CODE"
    HEADER = "HEADER"
    CONTENT_TYPE = "CONTENT_TYPE"
    RESPONSE_TIME = "RESPONSE_TIME"
    REQUIRED_FIELD = "REQUIRED_FIELD"
    FIELD_TYPE = "FIELD_TYPE"
    JSON_SCHEMA = "JSON_SCHEMA"
    ARRAY_STRUCTURE = "ARRAY_STRUCTURE"
    VARIABLE_EXTRACTION = "VARIABLE_EXTRACTION"
    BUSINESS_RULE = "BUSINESS_RULE"
